希望する短縮URLを指定できるようにする, エラー表示追加
dev-hato/hato-atama pull request #28
Opened 2021-01-10 19:11 UTC by massongit

希望する短縮URLを英数字で指定できるようにします。
また、エラー表示を追加します。

2021-01-10 23:37 UTC, Goryudyuma requested changes
- 希望するURLに?が許容されており、うまく飛べないケースがある
  - アルファベットと数字のみにした方がいいかも
- rawWantedShortURLはOptionにするべき
  - デフォルトではランダムで設定する。
- 希望するURLが既に取られていた場合は、エラーにするべきかも？

2021-01-10 23:37 UTC, Goryudyuma commented on server/main.go
> +		return nil, "", err
ここ、returnだけで大丈夫よ。
https://go-tour-jp.appspot.com/basics/7

2021-01-10 23:47 UTC, Goryudyuma commented on frontend/src/Main.elm
> +                    [ text (Url.toString model.url)
実際に生成されるのは `/l/` が入る
```suggestion
                    [ text <| (Url.toString model.url) ++ "/l/"
```

( `index.html` とか、APIのURL( `/api/` とか)と被らないように、短縮リンクはLinkのlを前につけてます。)

2021-01-11 00:06 UTC, massongit commented on server/main.go
> +		return nil, "", err
返り値を明記するなら明記する、しないならしないで統一した方がわかりやすいかと思ったけど、必ずしもそうしなくても問題ないか。

2021-01-11 00:08 UTC, massongit commented on server/main.go
> +		return nil, "", err
返り値を省略できるところは省略した。

2021-01-11 01:40 UTC, massongit commented
https://github.com/dev-hato/hato-atama/pull/28#pullrequestreview-564912666
>rawWantedShortURLはOptionにするべき

希望する短縮URLを指定しないのであれば、サーバーに `wanted_short_url` を送信しないようにする。
`wanted_short_url` が空文字列として送信された場合は空文字列を希望していると解釈する。

2021-01-11 09:44 UTC, massongit commented
* サーバー側で希望する短縮URLに対するバリデーションを行い、英数字のみを許容するようにした。
* `wanted_short_url` については指定しない場合は与えないようにした。
* 希望する短縮URLが既に使われていた場合はエラーを返すように実装した。これに伴い、エラー表示を追加した。

2021-01-11 10:08 UTC, Goryudyuma approved these changes

2021-01-11 10:08 UTC, merged